# This will start a mongodb database with an express frontend.
# Can be used as a testing environment
version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - omega

  server:
    build: ../server
    restart: always
    ports:
      - 8080:8080
    networks:
      - omega

  client:
    build: ../client
    restart: always
    ports:
      - 80:80
    networks:
      - omega
networks:
  omega:
